
services:
  postgres:
    image: postgres:15
    container_name: big_star_postgres
    restart: always
    env_file:
      - ${ENV_FILE:-.env.local}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data   # Volume
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql   # Initial PostgresSQL
    command: postgres -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    env_file:
      - ${ENV_FILE:-.env.local}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
               airflow webserver & airflow scheduler"

volumes:
  db_data: